import React, { useState } from 'react';
import { useStore } from '../store/useStore';
import { Code2, Settings, FolderOpen, Save, FileDown, X, Download, Copy, Check } from 'lucide-react';
import SettingsModal from './SettingsModal';
import { openFile, saveFile } from '../utils/fileSystem';

interface HeaderProps {
    editorContent: string;
    onFileOpen: (content: string) => void;
}

// Export Modal Component
const ExportModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
    const { threads, currentFile, language } = useStore();
    const [copied, setCopied] = useState(false);

    const generateReport = (): string => {
        const now = new Date();
        const timestamp = now.toLocaleString();
        const fileName = currentFile?.name || 'Untitled';

        let report = `# Code Review Report\n\n`;
        report += `**Generated:** ${timestamp}\n`;
        report += `**File:** ${fileName}\n`;
        report += `**Language:** ${language}\n`;
        report += `**Total Threads:** ${threads.length}\n\n`;
        report += `---\n\n`;

        if (threads.length === 0) {
            report += `*No review threads yet. Select code and ask AI for feedback!*\n`;
            return report;
        }

        threads.forEach((thread, index) => {
            const threadTitle = thread.range
                ? `Lines ${thread.range.startLineNumber}-${thread.range.endLineNumber}`
                : 'General Chat';

            report += `## Thread ${index + 1}: ${threadTitle}\n\n`;

            if (thread.codeContext) {
                report += `### Code Context\n\`\`\`${language}\n${thread.codeContext}\n\`\`\`\n\n`;
            }

            if (thread.messages.length > 0) {
                report += `### Conversation\n\n`;
                thread.messages.forEach((msg) => {
                    const role = msg.role === 'user' ? 'You' : 'AI';
                    const time = new Date(msg.timestamp).toLocaleTimeString();
                    report += `**${role}** *(${time})*:\n${msg.content}\n\n`;
                });
            } else {
                report += `*No messages in this thread*\n\n`;
            }

            report += `---\n\n`;
        });

        // Summary section
        const totalMessages = threads.reduce((acc, t) => acc + t.messages.length, 0);
        const aiMessages = threads.reduce(
            (acc, t) => acc + t.messages.filter((m) => m.role === 'assistant').length,
            0
        );

        report += `## Summary\n\n`;
        report += `- **Total Conversations:** ${threads.length}\n`;
        report += `- **Total Messages:** ${totalMessages}\n`;
        report += `- **AI Responses:** ${aiMessages}\n`;
        report += `- **Code Blocks Reviewed:** ${threads.filter((t) => t.codeContext).length}\n\n`;
        report += `---\n\n`;
        report += `*Report generated by AurelAI - AI-Powered Code Review Assistant*\n`;

        return report;
    };

    const report = generateReport();

    const handleDownload = () => {
        const blob = new Blob([report], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `code-review-report-${new Date().toISOString().split('T')[0]}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const handleCopy = async () => {
        try {
            await navigator.clipboard.writeText(report);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <div className="bg-gray-800 rounded-lg shadow-2xl max-w-3xl w-full max-h-[80vh] flex flex-col animate-in fade-in zoom-in duration-200">
                <div className="flex items-center justify-between px-6 py-4 border-b border-gray-700">
                    <div className="flex items-center gap-2">
                        <FileDown size={20} className="text-blue-400" />
                        <h2 className="text-lg font-semibold text-white">Export Feedback Report</h2>
                    </div>
                    <button
                        onClick={onClose}
                        className="text-gray-400 hover:text-white transition-colors"
                    >
                        <X size={20} />
                    </button>
                </div>

                <div className="flex-1 overflow-y-auto p-6">
                    <pre className="bg-gray-900 rounded-lg p-4 text-sm text-gray-300 whitespace-pre-wrap font-mono overflow-x-auto">
                        {report}
                    </pre>
                </div>

                <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-gray-700">
                    <button
                        onClick={handleCopy}
                        className="flex items-center gap-2 px-4 py-2 bg-gray-700 hover:bg-gray-600 text-white rounded-md transition-colors"
                    >
                        {copied ? <Check size={16} /> : <Copy size={16} />}
                        {copied ? 'Copied!' : 'Copy to Clipboard'}
                    </button>
                    <button
                        onClick={handleDownload}
                        className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md transition-colors"
                    >
                        <Download size={16} />
                        Download Markdown
                    </button>
                </div>
            </div>
        </div>
    );
};

const Header: React.FC<HeaderProps> = ({ editorContent, onFileOpen }) => {
    const { language, setLanguage, currentFile, setCurrentFile, threads } = useStore();
    const [isSettingsOpen, setIsSettingsOpen] = useState(false);
    const [isExportOpen, setIsExportOpen] = useState(false);

    const handleOpenFile = async () => {
        const result = await openFile();
        if (result) {
            setCurrentFile({ name: result.handle.name, handle: result.handle });
            onFileOpen(result.content);
        }
    };

    const handleSaveFile = async () => {
        const handle = await saveFile(editorContent, currentFile?.handle);
        if (handle && !currentFile) {
            setCurrentFile({ name: handle.name, handle });
        }
    };

    return (
        <>
            <header className="h-16 bg-gray-900 border-b border-gray-800 flex items-center justify-between px-6 shrink-0">
                <div className="flex items-center gap-2 text-blue-500">
                    <Code2 size={24} />
                    <span className="text-xl font-bold bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
                        AurelAI
                    </span>
                    {currentFile && (
                        <span className="text-sm text-gray-400 ml-2">
                            {currentFile.name}
                        </span>
                    )}
                </div>

                <div className="flex items-center gap-4">
                    <button
                        onClick={handleOpenFile}
                        className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors px-3 py-1.5 hover:bg-gray-800 rounded-md"
                        title="Open File"
                    >
                        <FolderOpen size={18} />
                        <span className="text-sm">Open</span>
                    </button>

                    <button
                        onClick={handleSaveFile}
                        className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors px-3 py-1.5 hover:bg-gray-800 rounded-md"
                        title="Save File"
                    >
                        <Save size={18} />
                        <span className="text-sm">Save</span>
                    </button>

                    <button
                        onClick={() => setIsExportOpen(true)}
                        disabled={threads.length === 0}
                        className="flex items-center gap-2 text-gray-400 hover:text-white disabled:text-gray-600 disabled:cursor-not-allowed transition-colors px-3 py-1.5 hover:bg-gray-800 disabled:hover:bg-transparent rounded-md"
                        title="Export Feedback Report"
                    >
                        <FileDown size={18} />
                        <span className="text-sm">Export</span>
                    </button>

                    <select
                        value={language}
                        onChange={(e) => setLanguage(e.target.value)}
                        className="bg-gray-800 text-white border border-gray-700 rounded-md px-3 py-1.5 text-sm focus:outline-none focus:border-blue-500 transition-colors"
                    >
                        <option value="javascript">JavaScript</option>
                        <option value="typescript">TypeScript</option>
                        <option value="python">Python</option>
                        <option value="java">Java</option>
                        <option value="cpp">C++</option>
                        <option value="c">C</option>
                        <option value="go">Go</option>
                        <option value="rust">Rust</option>
                        <option value="ruby">Ruby</option>
                        <option value="php">PHP</option>
                        <option value="html">HTML</option>
                        <option value="css">CSS</option>
                        <option value="json">JSON</option>
                    </select>

                    <button
                        onClick={() => setIsSettingsOpen(true)}
                        className="text-gray-400 hover:text-white transition-colors p-2 hover:bg-gray-800 rounded-full"
                        title="Settings"
                    >
                        <Settings size={20} />
                    </button>
                </div>
            </header>

            {isSettingsOpen && <SettingsModal onClose={() => setIsSettingsOpen(false)} />}
            {isExportOpen && <ExportModal onClose={() => setIsExportOpen(false)} />}
        </>
    );
};

export default Header;
